name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: format check
        run: npm run format:check
      - name: Test
        run: npm test -- --coverage
        env:
          CI: true
      
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: install surge
        run: npm install -g surge
      - name: Deploy to stage
        if: $GITHUB_EVENT_NAME == "push"
        run: npx surge --project ./build --domain lyrical-egg.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}